CREATE DATABASE IF NOT EXISTS mydb;

CREATE TABLE IF NOT EXISTS mydb.letters (
    entry_id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    letterround VARCHAR NOT NULL,
    

);

CREATE TABLE IF NOT EXISTS mydb.numbers (
    entry_id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    numberround INTEGER NOT NULL,

);
