CREATE DATABASE mydb;
CREATE table mydb.letters(
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    letters VARCHAR(80) NOT NULL
);

CREATE table mydb.numbers(
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    letters INTEGER(10) NOT NULL
);
