version: '3.7'
services:
  backend:
    image: zreginaldoz/backend:latest
    build: .
    ports:
    - target: 5003
      published: 5003
      protocol: tcp
    environment:
    - SECRET_KEY=secretkey
    networks:
    - my-network
  
  randnum_gen:
    image: zreginaldoz/randnum_gen:latest
    build: .
    ports:
    - target: 5002
      published: 5002
      protocol: tcp
    environment:
    - SECRET_KEY=secretkey
    networks:
    - my-network
  
  randstr_gen:
    image: zreginaldoz/randnum_gen:latest
    build: .
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
    environment:
    - SECRET_KEY=secretkey
    networks:
    - my-network
    
  frontend:
    image: zreginaldoz/frontend:latest
    build: .
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    environment:
    - SECRET_KEY=secretkey
    networks:
    - my-network
    depends_on:
    - backend

networks:
  my-network: