version: '3.7'
services:
  backend: 
    build: ./Backend
    image: zreginaldoz/backend:${Version}
    ports:
    - target: 5003
      published: 5003
      protocol: tcp
    deploy: 
     replicas: 4
    environment:
    - SECRET_KEY=hello
    - Version=${Version}
  
  randnum_gen:
    build: ./RandNum_Gen
    image: zreginaldoz/randnum_gen:${Version}
    ports:
    - target: 5002
      published: 5002
      protocol: tcp
    deploy:
     replicas: 4
    environment:
    - SSECRET_KEY=hello
    - Version=${Version}

  randstr_gen:
    build: ./RandStr_Gen
    image: zreginaldoz/randstr_gen:${Version}
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
    deploy:
     replicas: 4
    environment:
    - SECRET_KEY=hello
    - Version=${Version}
    
  frontend:
    image: zreginaldoz/frontend:${Version}
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    deploy:
     replicas: 4
    environment:
    - SECRET_KEY=hello
    - Version=${Version}

  mydb:
    build: ./mydb
    #image: zreginaldoz/mydb:v1
    ports:
    - 3306
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
    networks:
    - my-network
    #container_name: databass

    
networks:
  my-network:

