
- name: Git clone project
  git:
    repo: 'https://github.com/zReginaldo/Practical-SFIA-Project.git'
    dest: /home/jenkins/Practical-SFIA-Project

- name: Init a new swarm
  docker_swarm:
    state: present

- name: Build docker images
  docker_compose:
    project_src: /home/jenkins/Practical-SFIA-Project
    build: yes
  remote_user: jenkins
  
- name: Deploy stack from a compose file
  docker_stack:
    state: present
    name: Practical-SFIA-Project
    compose:
      - /home/jenkins/Practical-SFIA-Project/docker-compose.yaml