- name: Install Jenkins
  hosts: jenkins
  become: true
  tasks:

    - name: Install Java
      apt:
        name: openjdk-8-jdk
        state: present
        update_cache: yes

    - name: Download Jenkins Key
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
        state: present
    - name: Import Jenkins Repo
      apt_repository:
        repo: deb http://pkg.jenkins.io/debian-stable binary/
        state: present

    - name: Apt Install Jenkins 
      apt:
        name: jenkins
        state: present
        update_cache: yes

    - name: Start & Enable Jenkins
      systemd:
        name: jenkins
        state: started
        enabled: true

    - name: Sleep for 15 seconds and continue with play
      wait_for: timeout=15

    - name: insecure registry create Dir
      file:
        path: /etc/docker/
        state: directory
        mode: "0700"

    - name: insecure registry copy file
      copy:
        src: /home/qa-admin/Ansible/daemon.json
        dest: /etc/docker/daemon.json
        mode: u=rw,g=,o=

    - name: ssh folder
      file:
        path: /home/jenkins/.ssh
        state: directory
        mode: "0700"
        owner: jenkins
        group: jenkins

    - name: install private key
      copy:
        src: ~/.ssh/ansible_id_rsa
        dest: /home/jenkins/.ssh/id_rsa
        owner: jenkins
        group: jenkins
        mode: u=rw,g=,o=

    - name: Get init password Jenkins
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      changed_when: false
      register: result

    - name: Print init password Jenkins
      debug:
        var: result.stdout

    - name: Create a docker registry
      docker_container:
        name: registry
        image: registry:2
        ports:
          - "5000:5000"
