- name: 'download nginx using apt'
  apt:
    pkg:
    - nginx
    - git
    state: latest

- name: 'Initiate the nginx service'
  service:
    name: nginx
    state: started 

- name: 'Install nginx.conf'
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  register: nginx_config
  
- name: 'Restart nginx'
  service:
    name: nginx
    state: reloaded
  when: nginx_config.changed

    
